version: '2'
services:
    nginx:
        image: nginx:1.10.1
        ports:
            - "80:80"
        links:
            - php-fpm
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/conf.d:/etc/nginx/conf.d"
        volumes_from:
            - php-fpm
#       networks:
#           web:
#               ipv4_address: 172.19.238.2
    php-fpm:
        build: ./php-fpm
        volumes:
            - "./projects/:/var/www/projects"
            - "./php-fpm/php.ini:/usr/local/etc/php/php.ini"
#       networks:
#           web:
#               ipv4_address: 172.19.238.3


#networks:
#    web:
#        driver: bridge
#        ipam:
#            driver: default
#            config:
#                - subnet: 172.19.238.0/24
